import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/Arsenal-Bold.ttf",
  variable: "--font-geist-sans",
  weight: "700",
});
const geistMono = localFont({
  src: "./fonts/Arsenal-Regular.ttf",
  variable: "--font-geist-mono",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="relative max-w-[1440px] w-full mx-auto h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
